### ISSUE TITLE
[PE-D][Tester C] :bug: Bug: App crashes when UI is being resized

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-2/tp#169]
## Expected behaviour 
- the app should not crash

## Current behaviour
- the app crashes 

## How to reproduce
- run `java -jar InTrack.jar`
- constantly resize the app 
- eventually the app would crash

## Screenshots

![Screenshot 2022-10-28 at 4.04.50 PM.png](https://raw.githubusercontent.com/ShenyiCui/ped/main/files/31af6b12-4c15-4e71-9fd9-dd112c8c186f.png)

## Logs
[hs_err_pid18351.log](https://raw.githubusercontent.com/ShenyiCui/ped/main/files/17118e1e-4aaf-4188-be35-40961d1a9429.log)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ShenyiCui/ped#3

**Comment by jetlfj** [comment]
Unfortunately, we are unable to replicate this issue on our side with both Windows and MacOS systems. Also, this is likely classified under extreme user behaviour as a a normal user would not be constantly resizing the application to cause such an issue.
