### ISSUE TITLE
[PE-D][Tester C] :bug: Bug: error messages appear in the wrong order

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T11-2/tp#180]
## Description (Current behaviour)
If I'm trying to edit an internship before I select one and enter the information incorrectly e.g. wrong format then the error messages appear in the wrong order

## Expected behaviour
- The error message telling me that I have yet to select an internship should have priority
- The reason being that if I edit the message to make it match, I will again be forced to delete it to first select a task. 

## How to reproduce
- edit e/ something
- [shows error message on wrong email format]
- [correct to correct email format]
- [shows error on not selecting internship]
- [forced to delete command]

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ShenyiCui/ped#6

**Comment by jetlfj** [comment]
Unfortunately, this is a limitation of the current implementation. The individual `Parser` classes do not have access to the `Model` and thus cannot determine whether an internship application has been selected. A possible workaround would have been to move the `ParserUtil` methods into the `Command` classes, but that would somewhat defeat the purpose of having the `Parser` classes in the first place.
We decided that the current implementation is acceptable as a normal user would have to select the internship application first to view its details before deciding to make any changes.
