### ISSUE TITLE
[PE-D][Tester B] Left panel displays no upcoming tasks when there are clearly added tasks

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-2/tp#189]
After adding multiple tasks, the left panel display for the internship position I created still reflects as `No upcoming tasks`:

![image.png](https://raw.githubusercontent.com/Kok-je/ped/main/files/0622b5ea-8bf7-4f58-8e29-d6f3e1ba99a1.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: Kok-je/ped#5

**Comment by bigcrushes** [comment]
This is the intended behaviour as it will only show the most recent upcoming task (tasks after the current time). It does not make sense to show tasks that have already passed as upcoming tasks.
